### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified. : '/tmp/policy/'

### ISSUE THREAD

**Issue by xlws1** [SihongHo/Robust_MARL_with_State_Uncertainty#1]
Hello author, when I run python train.py, the following error occurs:

If you depend on functionality not listed there, please file an issue.

Namespace(adv_policy='rmaac', batch_size=1024, benchmark=False, benchmark_dir='./benchmark_files/', benchmark_iters=100000, constraint_epsilon=0.5, display=False, do_not_use_send_email
=True, exp_name=None, gamma=0.95, good_policy='rmaac', load_dir='', lr=0.01, lr_adv=0.01, max_episode_len=25, noise_policy='rmaac', noise_type='Linear', noise_variance=1, num_adversari
es=0, num_episodes=60000, num_units=64, plots_dir='./learning_curves/', restore=False, save_dir='/tmp/policy/', save_rate=1000, scenario='simple', server_name='MyServer')
Traceback (most recent call last):
  File "train.py", line 304, in <module>
    os.mkdir(arglist.save_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified. : '/tmp/policy/'

**Comment by sihongho** [comment]
You may try to create this path before you run

**Comment by zfz-star** [comment]
作者你好，在运行simple以外的环境时，出现以下错误：如运行python train.py --scenario simple_push
Traceback (most recent call last):
  File "train.py", line 304, in <module>
    train(arglist)
  File "train.py", line 187, in train
    adv_action_n = np.clip(adv_action_n, a_min = -arglist.constraint_epsilon, a_max = arglist.constraint_epsilon)
  File "D:\ProgramData\anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 1775, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out)
  File "D:\ProgramData\anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by sihongho** [comment]
We have not encountered this issue before. It might be related to the version of NumPy being used. Please verify your NumPy version and ensure compatibility with the codebase. If the issue persists, consider downgrading or upgrading NumPy to a stable version that aligns with the project’s dependencies.

**Comment by sihongho** [comment]
fixed

**Comment by zfz-star** [comment]
我下载的依赖项是Python (3.5.4), OpenAI gym (0.10.5), tensorflow (1.8.0), numpy (1.14.5)，除了simple，simple_reference，simple_spread环境意外，都出现报错
Traceback (most recent call last):
  File "D:\Anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'clip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 307, in <module>
    train(arglist)
  File "train.py", line 190, in train
    adv_action_n = np.clip(adv_action_n, a_min = -arglist.constraint_epsilon, a_max = arglist.constraint_epsilon)
  File "D:\Anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 1775, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out)
  File "D:\Anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 62, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "D:\Anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 42, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by zfz-star** [comment]
When I train in other environments, some environments can run, but some will report errors.
for example when i run :python train.py --scenario simple_crypto/simple_tag

Starting iterations...
Traceback (most recent call last):
  File "D:\Anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'clip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 307, in <module>
    train(arglist)
  File "train.py", line 190, in train
    adv_action_n = np.clip(adv_action_n, a_min = -arglist.constraint_epsilon, a_max = arglist.constraint_epsilon)
  File "D:\Anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 1775, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out)
  File "D:\Anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 62, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "D:\Anaconda3\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 42, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I installed the following dependency packages:Python (3.5.4), OpenAI gym (0.10.5), tensorflow (1.8.0), numpy (1.14.5),May I ask what the reason is？My multi-agent environment was downloaded from your GitHub，not OpenAI.Does this matter?

**Comment by sihongho** [comment]
We didn't encouter such an issue, but you may try to convert adv_action_n to a NumPy array before applying the np.clip function.
