### ISSUE TITLE
Some experiments in certain environments cannot run

### ISSUE THREAD

**Issue by xlws1** [SihongHo/Robust_MARL_with_State_Uncertainty#3]
When I train in other environments, some environments can run, but some will report errors.
for example when i run :python train.py --scenario simple_crypto/simple_tag  

Starting iterations...
Traceback (most recent call last):
  File "D:\Anaconda\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'clip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 305, in <module>
    train(arglist)
  File "train.py", line 188, in train
    adv_action_n = np.clip(adv_action_n, a_min = -arglist.constraint_epsilon, a_max = arglist.constraint_epsilon)
  File "D:\Anaconda\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 1775, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out)
  File "D:\Anaconda\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 62, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "D:\Anaconda\envs\rmaac\lib\site-packages\numpy\core\fromnumeric.py", line 42, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

 I installed the following dependency packages:Python (3.5.4), OpenAI gym (0.10.5), tensorflow (1.8.0), numpy (1.14.5),May I ask what the reason is？My multi-agent environment was downloaded from your GitHub，not OpenAI.Does this matter?

**Comment by sihongho** [comment]
We didn't enouter such an inssue. You may try to convert adv_action_n to a NumPy array before applying the np.clip function.
